apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: servicenow-change-approval
description: Complete ServiceNow Change Request lifecycle with approval gate

inputs:
  url:
    required: true
    description: ServiceNow instance URL (e.g., https://dev12345.service-now.com)
  username:
    required: true
    description: ServiceNow username
  password:
    required: true
    description: ServiceNow password
  short-description:
    required: true
    description: Short description for the Change Request
  assignment-group:
    required: false
    default: "Change Management"
    description: Assignment group for the Change Request
  cr-type:
    required: false
    default: "normal"
    description: Type of Change Request (normal, emergency, standard)
  poll-interval:
    required: false
    default: "1"
    description: Polling interval in minutes
  poll-duration:
    required: false
    default: "10"
    description: Maximum polling duration in minutes
  close-notes:
    required: false
    default: "Successfully completed"
    description: Notes to add when closing the Change Request

outputs:
  cr-sys-id:
    description: ServiceNow Change Request system ID
    value: ${{ steps.outputs.outputs.cr-sys-id }}
  cr-number:
    description: ServiceNow Change Request number
    value: ${{ steps.outputs.outputs.cr-number }}
  approval-status:
    description: Approval status (approved/rejected/timeout)
    value: ${{ steps.outputs.outputs.approval-status }}
  cr-state:
    description: Final Change Request state
    value: ${{ steps.outputs.outputs.cr-state }}
  cr-url:
    description: ServiceNow Change Request URL
    value: ${{ steps.outputs.outputs.cr-url }}

runs:
  using: composite
  steps:
    - id: create-cr
      name: Create ServiceNow Change Request
      uses: cloudbees-io/servicenow@v1
      with:
        url: ${{ inputs.url }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        action-type: create
        cr-type: ${{ inputs.cr-type }}
        short-description: ${{ inputs.short-description }}

    - id: update-cr-assess
      name: Update CR to Assess state
      uses: cloudbees-io/servicenow@v1
      with:
        url: ${{ inputs.url }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        action-type: update
        sys-id: ${{ fromJSON(steps.create-cr.outputs.servicenow-output).sys_id }}
        state: Assess
        assignment-group: ${{ inputs.assignment-group }}

    - id: update-cr-authorize
      name: Update CR to Authorize state
      uses: cloudbees-io/servicenow@v1
      with:
        url: ${{ inputs.url }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        action-type: update
        sys-id: ${{ fromJSON(steps.create-cr.outputs.servicenow-output).sys_id }}
        state: Authorize

    - id: update-cr-scheduled
      name: Update CR to Scheduled state
      uses: cloudbees-io/servicenow@v1
      with:
        url: ${{ inputs.url }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        action-type: update
        sys-id: ${{ fromJSON(steps.create-cr.outputs.servicenow-output).sys_id }}
        state: Scheduled

    - id: update-cr-implement
      name: Update CR to Implement state
      uses: cloudbees-io/servicenow@v1
      with:
        url: ${{ inputs.url }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        action-type: update
        sys-id: ${{ fromJSON(steps.create-cr.outputs.servicenow-output).sys_id }}
        state: Implement

    - id: update-cr-review
      name: Update CR to Review state
      uses: cloudbees-io/servicenow@v1
      with:
        url: ${{ inputs.url }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        action-type: update
        sys-id: ${{ fromJSON(steps.create-cr.outputs.servicenow-output).sys_id }}
        state: Review

    - id: wait-for-approval
      name: Wait for ServiceNow approval
      uses: cloudbees-io/servicenow-poll-for-approval@v1
      with:
        url: ${{ inputs.url }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        cr-number: ${{ fromJSON(steps.create-cr.outputs.servicenow-output).number }}
        poll-interval: ${{ inputs.poll-interval }}
        poll-duration: ${{ inputs.poll-duration }}
        state-field-value: Review
        approval-field-value-approved: Approved
        approval-field-value-rejected: Rejected

    - id: close-cr
      name: Close ServiceNow Change Request
      uses: cloudbees-io/servicenow@v1
      with:
        url: ${{ inputs.url }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        action-type: update
        sys-id: ${{ fromJSON(steps.create-cr.outputs.servicenow-output).sys_id }}
        short-description: ${{ inputs.short-description }}
        state: Closed
        close-code: Successful
        close-notes: ${{ inputs.close-notes }}

    - id: outputs
      name: Extract and format outputs
      uses: docker://alpine:3.20
      shell: sh
      env:
        CREATE_OUTPUT: ${{ steps.create-cr.outputs.servicenow-output }}
        APPROVAL_OUTPUT: ${{ steps.wait-for-approval.outputs.servicenow-output }}
        CLOSE_OUTPUT: ${{ steps.close-cr.outputs.servicenow-output }}
        SERVICENOW_URL: ${{ inputs.url }}
      run: |
        set -eu
        apk add --no-cache jq > /dev/null 2>&1

        # Extract CR info from create step
        CR_SYS_ID=$(echo "$CREATE_OUTPUT" | jq -r '.sys_id // "unknown"')
        CR_NUMBER=$(echo "$CREATE_OUTPUT" | jq -r '.number // "unknown"')

        # Extract approval status from poll step
        APPROVAL_STATUS=$(echo "$APPROVAL_OUTPUT" | jq -r '.approval // "unknown"')

        # Extract final state from close step
        CR_STATE=$(echo "$CLOSE_OUTPUT" | jq -r '.state // "Closed"')

        # Build ServiceNow CR URL
        SN_BASE_URL=$(echo "$SERVICENOW_URL" | sed 's:/*$::')
        CR_URL="${SN_BASE_URL}/change_request.do?sys_id=${CR_SYS_ID}"

        # Write outputs (use printf to avoid trailing newline)
        printf "%s" "$CR_SYS_ID" > "$CLOUDBEES_OUTPUTS/cr-sys-id"
        printf "%s" "$CR_NUMBER" > "$CLOUDBEES_OUTPUTS/cr-number"
        printf "%s" "$APPROVAL_STATUS" > "$CLOUDBEES_OUTPUTS/approval-status"
        printf "%s" "$CR_STATE" > "$CLOUDBEES_OUTPUTS/cr-state"
        printf "%s" "$CR_URL" > "$CLOUDBEES_OUTPUTS/cr-url"

        echo "ServiceNow CR: $CR_NUMBER (ID: $CR_SYS_ID)"
        echo "Approval Status: $APPROVAL_STATUS"
        echo "Final State: $CR_STATE"
        echo "CR URL: $CR_URL"

    - id: display-summary
      name: Display ServiceNow Change Request Summary
      uses: docker://alpine:3.20
      shell: sh
      env:
        CREATE_OUTPUT: ${{ steps.create-cr.outputs.servicenow-output }}
        APPROVAL_OUTPUT: ${{ steps.wait-for-approval.outputs.servicenow-output }}
        CLOSE_OUTPUT: ${{ steps.close-cr.outputs.servicenow-output }}
      run: |
        apk add --no-cache jq > /dev/null 2>&1

        CR_NUMBER=$(echo "$CREATE_OUTPUT" | jq -r '.number')
        CR_SYS_ID=$(echo "$CREATE_OUTPUT" | jq -r '.sys_id')
        APPROVAL=$(echo "$APPROVAL_OUTPUT" | jq -r '.approval')
        STATE=$(echo "$CLOSE_OUTPUT" | jq -r '.state')

        echo ""
        echo "========================================="
        echo "ServiceNow Change Request Details"
        echo "========================================="
        echo "Change Record: $CR_NUMBER"
        echo ""
        echo "Field             Value"
        echo "----------------  ----------------------"
        echo "CR Number         $CR_NUMBER"
        echo "CR System ID      $CR_SYS_ID"
        echo "Approval Status   ✅ $APPROVAL"
        echo "Final State       $STATE"
        echo ""
        echo "Change Request approved and ready for deployment"
        echo "========================================="
        echo ""

    - id: publish-evidence
      name: Publish ServiceNow evidence
      kind: build
      uses: cloudbees-io/publish-evidence-item@v1
      with:
        content: |
          ## ServiceNow Change Request Details

          **Change Record: ${{ fromJSON(steps.create-cr.outputs.servicenow-output).number }}**

          | Field | Value |
          |-------|-------|
          | **CR Number** | ${{ fromJSON(steps.create-cr.outputs.servicenow-output).number }} |
          | **CR System ID** | ${{ fromJSON(steps.create-cr.outputs.servicenow-output).sys_id }} |
          | **Approval Status** | ✅ ${{ fromJSON(steps.wait-for-approval.outputs.servicenow-output).approval }} |
          | **Final State** | ${{ fromJSON(steps.close-cr.outputs.servicenow-output).state }} |

          ---
          *Change Request approved and ready for deployment*
        format: MARKDOWN
